on:
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: echo test! 2>&1 | tee logs.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
